// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('e:/ReactNative/work/Francisco/general-inventory-system-mobile-app/node_modules/react');
var { Component } = React;
var ReactNative = require('e:/ReactNative/work/Francisco/general-inventory-system-mobile-app/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Inventory', appParameters);
});
require('e:/ReactNative/work/Francisco/general-inventory-system-mobile-app/index.js');